import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NavBar from "@/components/NavBar";
import "./globals.css";
import NavBear from "@/components/NavBear";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "No Pool Productions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/dbw5tsh.css" />
      </head>
      <body>
        <NavBear />
        {children}
        <Footer />
      </body>
    </html>
  );
}
