import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { ContactProvider } from "@/contexts/ContactContext";
import ContactOverlay from "@/components/ContactOverlay";
import ContactOverlayWrapper from "@/contexts/ContactOverlayWrapper";

export const metadata: Metadata = {
  title: "No Pool Productions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/dbw5tsh.css" />
      </head>
      <body>
        <ContactProvider>
          <NavBar />
          {children}
          <Footer />
          <ContactOverlayWrapper />
        </ContactProvider>
      </body>
    </html>
  );
}